services:
  - type: web
    name: daylen-coffee
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
