// This file is auto-generated by the Ziggy package
import route from 'ziggy-js';

// This will be replaced with the actual routes in the build process
export default route;

export const Ziggy = window.Ziggy || {};
